
[workspace]
members = [
    "guessing_game",
    "ownership",
    "first_word",
    "managing_growing_project_1",
    "modules",
    "common_collection",
    "error_handling",
    "generic_traits_lifetime",
    "io_project",
    "funtional_language",
    "smart_pointer",
]